# Sub-commands available via phrozn executable
---
help:
    name: help
    aliases: [h, ?]
    short_name: ?, h
    description: Phrozn usage manual
    arguments:
        topic:
            help_name: sub-command
            description: Help topic
            optional: true
