# Meta information about Phrozn
---
name: Phrozn
version: &ver "0.1 alpha"
credits: Vic Farazdagi

command:
    name: /usr/bin/phrozn
    description: Phrozn - static site generator for PHP
    version: *ver
    add_help_option: false
    options:
        help:
            short_name:     -h
            long_name:      --help
            description:    Show this help message
            action:         StoreTrue
            callback:       [HelpExtended, execute]
            action_params: 
                use_colors: true
