# Meta information about Phrozn
---
name: Phrozn
description: &desc Phrozn is extremely flexible static site generator for PHP.
version: &ver "0.1.0"
author: Victor Farazdagi

command:
    name: /usr/bin/phrozn
    description: *desc
    version: *ver
    add_help_option: false
    options:
        help:
            short_name:     -h
            long_name:      --help
            description:    Show this help message
            action:         StoreTrue
            callback:       [HelpExtended, execute]
            action_params: 
                use_colors: true
