# phr init 
---
command:
    name: &name initialize
    aliases: [init]
    description: Phrozn usage manual
    arguments:
        topic:
            help_name: sub-command
            description: Help topic
            optional: true

# callback
callback: [Init, execute]

# documentation
docs:
    name: initialize (init) 
    summary: Initialize Phrozn project
    description: |
        This command creates empty phrozn site.

        If output PATH not provided, current directory is assumed.
    usage: %bphrozn%n %ginit%n [PATH]
    examples: |
        To create project in current directory:
        %bphrozn%n %ginit%n 

        To create project in specified directory PATH:
        %bphrozn%n %ginit%n PATH

        To create project in current directory (path specified explicitly):
        %bphrozn%n %ginit%n .
